### ISSUE TITLE
Zombie Talisman cooldown nonfunctional

### ISSUE THREAD

**Issue by STS15** [STS15/Fargos-Talismans#11]
Neoforge: 21.1.31
Fargos Talismans: 1.21-2.0.7

Zombie Talisman cooldown doesnt seem to be working

**Comment by maher-nakesh** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by STS15** [comment]
Cooldown was set low for testing, set to proper value.
