### ISSUE TITLE
gui? where?

### ISSUE THREAD

**Issue by Dorrivix** [STS15/Fargos-Talismans#20]
### Modpack

Yes

### Neoforge Version

21.1.51

### Mod Version

1.21.1 - 2.1.0

### Describe the issue

documentation on how to access the gui would be appreciated. I've only just found the command to open it through trial and error of trying every single other way of opening a gui.

**Comment by Dorrivix** [comment]
sorry, uh, was putting in for bug because I was originally making a bug report, this is somewhere in the middle of feature req, and bug. bug because I don't know if or where a button for the gui exists outside of using commands, and feature for the documentation.

**Comment by STS15** [comment]
Gui info has been provided in the patchouli book in the latest update.  I will update the readme to reflect.
