### ISSUE TITLE
I made a Chinese Simplified Chinese translation

### ISSUE THREAD

**Issue by shenyx110** [STS15/Fargos-Talismans#21]
### What should be added or changed?

I made a Chinese Simplified Chinese translation

**Comment by shenyx110** [comment]
{
    "item.fargostalismans.redstone_talisman": "红石护身符",
    "item.fargostalismans.amethyst_talisman": "紫水晶护身符",
    "item.fargostalismans.diamond_talisman": "钻石护身符",
    "item.fargostalismans.lapis_talisman": "青金石护身符",
    "item.fargostalismans.iron_talisman": "铁护身符",
    "item.fargostalismans.emerald_talisman": "绿宝石护身符",
    "item.fargostalismans.gold_talisman": "金护身符",
    "item.fargostalismans.copper_talisman": "铜护身符",
    "item.fargostalismans.wither_talisman": "凋零护身符",
    "item.fargostalismans.earth_talisman": "大地护身符",
    "item.fargostalismans.water_talisman": "水护身符",
    "item.fargostalismans.fire_talisman": "火护身符",
    "item.fargostalismans.air_talisman": "空气护身符",
    "item.fargostalismans.apple_talisman": "苹果护身符",
    "item.fargostalismans.nether_star_talisman": "下界之星护身符",
    "item.fargostalismans.obsidian_talisman": "黑曜石护身符",
    "item.fargostalismans.dragon_talisman": "龙护身符",
    "item.fargostalismans.mooshroom_talisman": "哞菇护身符",
    "item.fargostalismans.skeleton_talisman": "骷髅护身符",
    "item.fargostalismans.zombie_talisman": "僵尸护身符",
    "item.fargostalismans.blaze_talisman": "烈焰人护身符",
    "item.fargostalismans.pickaxe_talisman": "镐护身符",
    "item.fargostalismans.vindicator_talisman": "卫道士护身符",
    "item.fargostalismans.ghast_talisman": "恶魂护身符",
    "item.fargostalismans.creeper_talisman": "苦力怕护身符",
    "item.fargostalismans.vampiric_talisman": "吸血鬼护身符",
    "item.fargostalismans.enchanting_talisman": "附魔护身符",
    "item.fargostalismans.librarian_talisman": "图书管理员护身符",
    "item.fargostalismans.witch_talisman": "女巫护身符",
    "item.fargostalismans.shulker_talisman": "潜影贝护身符",
    "item.fargostalismans.undying_talisman": "不死护身符",
    "item.fargostalismans.battle_talisman": "战斗护身符",
    "item.fargostalismans.cactus_talisman": "仙人掌护身符",
    "item.fargostalismans.void_talisman": "虚空护身符",
    "item.fargostalismans.thorny_talisman": "荆棘护身符",
    "item.fargostalismans.iron_golem_talisman": "铁傀儡护身符",
    "item.fargostalismans.architect_talisman": "建筑师护身符",
    "item.fargostalismans.enderman_talisman": "末影人护身符",
    "item.fargostalismans.arctic_talisman": "北极护身符",
    "item.fargostalismans.spectral_talisman": "幽灵护身符",
    "item.fargostalismans.glowstone_talisman": "荧石护身符",
    
    "item.fargostalismans.tooltip.redstone_talisman.title": "红石",
    "item.fargostalismans.tooltip.amethyst_talisman.title": "紫水晶",
    "item.fargostalismans.tooltip.diamond_talisman.title": "钻石",
    "item.fargostalismans.tooltip.lapis_talisman.title": "青金石",
    "item.fargostalismans.tooltip.iron_talisman.title": "铁",
    "item.fargostalismans.tooltip.emerald_talisman.title": "绿宝石",
    "item.fargostalismans.tooltip.gold_talisman.title": "金",
    "item.fargostalismans.tooltip.copper_talisman.title": "铜",
    "item.fargostalismans.tooltip.wither_talisman.title": "凋零",
    "item.fargostalismans.tooltip.earth_talisman.title": "大地",
    "item.fargostalismans.tooltip.water_talisman.title": "水",
    "item.fargostalismans.tooltip.fire_talisman.title": "火",
    "item.fargostalismans.tooltip.air_talisman.title": "空气",
    "item.fargostalismans.tooltip.apple_talisman.title": "苹果",
    "item.fargostalismans.tooltip.nether_star_talisman.title": "下界之星",
    "item.fargostalismans.tooltip.obsidian_talisman.title": "黑曜石",
    "item.fargostalismans.tooltip.dragon_talisman.title": "龙",
    "item.fargostalismans.tooltip.mooshroom_talisman.title": "哞菇",
    "item.fargostalismans.tooltip.skeleton_talisman.title": "骷髅",
    "item.fargostalismans.tooltip.zombie_talisman.title": "僵尸",
    "item.fargostalismans.tooltip.blaze_talisman.title": "烈焰人",
    "item.fargostalismans.tooltip.pickaxe_talisman.title": "镐",
    "item.fargostalismans.tooltip.vindicator_talisman.title": "卫道士",
    "item.fargostalismans.tooltip.ghast_talisman.title": "恶魂",
    "item.fargostalismans.tooltip.creeper_talisman.title": "苦力怕",
    "item.fargostalismans.tooltip.vampiric_talisman.title": "吸血鬼",
    "item.fargostalismans.tooltip.enchanting_talisman.title": "附魔",
    "item.fargostalismans.tooltip.librarian_talisman.title": "图书管理员",
    "item.fargostalismans.tooltip.witch_talisman.title": "女巫",
    "item.fargostalismans.tooltip.shulker_talisman.title": "潜影贝",
    "item.fargostalismans.tooltip.undying_talisman.title": "不死",
    "item.fargostalismans.tooltip.battle_talisman.title": "战斗",
    "item.fargostalismans.tooltip.cactus_talisman.title": "仙人掌",
    "item.fargostalismans.tooltip.void_talisman.title": "虚空",
    "item.fargostalismans.tooltip.thorny_talisman.title": "荆棘",
    "item.fargostalismans.tooltip.iron_golem_talisman.title": "铁傀儡",
    "item.fargostalismans.tooltip.architect_talisman.title": "建筑师",
    "item.fargostalismans.tooltip.enderman_talisman.title": "末影人",
    "item.fargostalismans.tooltip.arctic_talisman.title": "北极",
    "item.fargostalismans.tooltip.spectral_talisman.title": "幽灵",
    "item.fargostalismans.tooltip.glowstone_talisman.title": "荧石",
    
    "item.fargostalismans.tooltip.redstone_talisman": "随着时间缓慢修复护甲耐久度",
    "item.fargostalismans.tooltip.amethyst_talisman": "免疫投射物伤害",
    "item.fargostalismans.tooltip.diamond_talisman": "减少20%的所有伤害",
    "item.fargostalismans.tooltip.lapis_talisman": "吸引经验球到玩家身边",
    "item.fargostalismans.tooltip.iron_talisman": "减少5%的所有伤害",
    "item.fargostalismans.tooltip.emerald_talisman": "对掠夺者和卫道士造成额外伤害",
    "item.fargostalismans.tooltip.gold_talisman": "猪灵不会攻击你",
    "item.fargostalismans.tooltip.copper_talisman": "增加物品拾取范围并吸引地上的物品",
    "item.fargostalismans.tooltip.wither_talisman": "免疫凋零效果",
    "item.fargostalismans.tooltip.earth_talisman": "用空手将泥土转换为草方块",
    "item.fargostalismans.tooltip.water_talisman": "在水下提供无限空气",
    "item.fargostalismans.tooltip.fire_talisman": "免疫所有燃烧伤害",
    "item.fargostalismans.tooltip.air_talisman": "免疫摔落伤害",
    "item.fargostalismans.tooltip.apple_talisman": "增加25%的治疗效果",
    "item.fargostalismans.tooltip.nether_star_talisman": "增加暴击伤害和暴击几率",
    "item.fargostalismans.tooltip.obsidian_talisman": "免疫爆炸伤害",
    "item.fargostalismans.tooltip.dragon_talisman": "免疫魔法伤害",
    "item.fargostalismans.tooltip.mooshroom_talisman": "站在菌丝上时恢复生命值",
    "item.fargostalismans.tooltip.skeleton_talisman": "增加箭矢伤害",
    "item.fargostalismans.tooltip.zombie_talisman": "在一段时间未攻击后，暂时增加攻击速度",
    "item.fargostalismans.tooltip.blaze_talisman": "点燃附近的怪物",
    "item.fargostalismans.tooltip.pickaxe_talisman": "采矿速度加倍",
    "item.fargostalismans.tooltip.vindicator_talisman": "切换武器后提升下一次攻击的伤害",
    "item.fargostalismans.tooltip.ghast_talisman": "对周围的怪物施加虚弱效果",
    "item.fargostalismans.tooltip.creeper_talisman": "跳跃时爆炸",
    "item.fargostalismans.tooltip.vampiric_talisman": "从敌人处汲取生命来治疗玩家",
    "item.fargostalismans.tooltip.enchanting_talisman": "移除主手或副手持有物品上的诅咒",
    "item.fargostalismans.tooltip.librarian_talisman": "增加50%的经验获取",
    "item.fargostalismans.tooltip.witch_talisman": "女巫会对你投掷有益的药水并对攻击者施加失明效果",
    "item.fargostalismans.tooltip.shulker_talisman": "免疫潜影贝的漂浮效果",
    "item.fargostalismans.tooltip.undying_talisman": "在死亡时复活并恢复满血",
    "item.fargostalismans.tooltip.battle_talisman": "在受到伤害后短暂获得无敌效果",
    "item.fargostalismans.tooltip.cactus_talisman": "反射部分伤害给攻击者",
    "item.fargostalismans.tooltip.void_talisman": "有小概率避免致命伤害并免疫掉入虚空",
    
    "item.fargostalismans.tooltip.thorny_talisman": "抵消甜浆果灌木伤害",
    "item.fargostalismans.tooltip.iron_golem_talisman": "增加玩家的生命值",
    "item.fargostalismans.tooltip.architect_talisman": "增加放置方块的范围",
    "item.fargostalismans.tooltip.enderman_talisman": "防止苦力怕攻击",
    "item.fargostalismans.tooltip.arctic_talisman": "抵消冰冻效果伤害",
    "item.fargostalismans.tooltip.spectral_talisman": "防止幻影攻击",
    "item.fargostalismans.tooltip.glowstone_talisman": "使玩家看不见的附近怪物发光",
    
    "item.fargostalismans.fired_talisman": "燃烧的护符",
    "item.fargostalismans.poisoned_talisman": "中毒的护符",
    "item.fargostalismans.withered_talisman": "枯萎的护符",
    "item.fargostalismans.blinded_talisman": "失明的护符",
    "item.fargostalismans.fatigued_talisman": "疲惫的护符",
    "item.fargostalismans.slowed_talisman": "减速的护符",
    "item.fargostalismans.nauseated_talisman": "恶心的护符",
    "item.fargostalismans.weakened_talisman": "虚弱的护符",
    "item.fargostalismans.tooltip.fired_talisman.title": "燃烧",
    "item.fargostalismans.tooltip.poisoned_talisman.title": "中毒",
    "item.fargostalismans.tooltip.withered_talisman.title": "枯萎",
    "item.fargostalismans.tooltip.blinded_talisman.title": "失明",
    "item.fargostalismans.tooltip.fatigued_talisman.title": "疲惫",
    "item.fargostalismans.tooltip.slowed_talisman.title": "减速",
    "item.fargostalismans.tooltip.nauseated_talisman.title": "恶心",
    "item.fargostalismans.tooltip.weakened_talisman.title": "虚弱",
    "item.fargostalismans.tooltip.fired_talisman": "在燃烧时，你造成的伤害增加25%",
    "item.fargostalismans.tooltip.poisoned_talisman": "在中毒时，你造成的伤害增加25%",
    "item.fargostalismans.tooltip.withered_talisman": "在枯萎时，你造成的伤害增加25%",
    "item.fargostalismans.tooltip.blinded_talisman": "在失明时，你造成的伤害增加25%",
    "item.fargostalismans.tooltip.fatigued_talisman": "在疲惫时，你造成的伤害增加25%",
    "item.fargostalismans.tooltip.slowed_talisman": "在减速时，你造成的伤害增加25%",
    "item.fargostalismans.tooltip.nauseated_talisman": "在恶心时，你造成的伤害增加25%",
    "item.fargostalismans.tooltip.weakened_talisman": "在虚弱时，你造成的伤害增加25%",
    
    "item.fargostalismans.sun_talisman": "太阳护符",
    "item.fargostalismans.true_sun_talisman": "真正的太阳护符",
    "item.fargostalismans.storm_talisman": "风暴护符",
    "item.fargostalismans.rain_talisman": "雨天护符",
    "item.fargostalismans.snowy_talisman": "雪天护符",
    "item.fargostalismans.day_talisman": "白天护符",
    "item.fargostalismans.night_talisman": "夜晚护符",
    "item.fargostalismans.full_moon_talisman": "满月护符",
    "item.fargostalismans.tooltip.sun_talisman.title": "太阳",
    "item.fargostalismans.tooltip.true_sun_talisman.title": "真正的太阳",
    "item.fargostalismans.tooltip.storm_talisman.title": "风暴",
    "item.fargostalismans.tooltip.rain_talisman.title": "雨天",
    "item.fargostalismans.tooltip.snowy_talisman.title": "雪天",
    "item.fargostalismans.tooltip.day_talisman.title": "白天",
    "item.fargostalismans.tooltip.night_talisman.title": "夜晚",
    "item.fargostalismans.tooltip.full_moon_talisman.title": "满月",
    "item.fargostalismans.tooltip.sun_talisman": "晴天时伤害增加5%",
    "item.fargostalismans.tooltip.true_sun_talisman": "在无遮挡的晴天时伤害增加5%",
    "item.fargostalismans.tooltip.storm_talisman": "闪电/雷暴期间伤害增加15%",
    "item.fargostalismans.tooltip.rain_talisman": "雨天时游泳速度增加50%",
    "item.fargostalismans.tooltip.snowy_talisman": "雪暴期间伤害增加20%",
    "item.fargostalismans.tooltip.day_talisman": "白天时伤害增加5%",
    "item.fargostalismans.tooltip.night_talisman": "夜晚时护甲增加10%",
    "item.fargostalismans.tooltip.full_moon_talisman": "满月时伤害增加10%",
    
    "item.fargostalismans.mutual_sword_talisman": "相互剑护符",
    "item.fargostalismans.mutual_bow_talisman": "相互弓箭护符",
    "item.fargostalismans.mutual_trident_talisman": "相互三叉戟护符",
    "item.fargostalismans.health_sharing_talisman": "生命共享护符",
    "item.fargostalismans.food_sharing_talisman": "食物共享护符",
    "item.fargostalismans.turtle_talisman": "乌龟护符",
    "item.fargostalismans.tooltip.mutual_sword_talisman.title": "相互剑",
    "item.fargostalismans.tooltip.mutual_bow_talisman.title": "相互弓箭",
    "item.fargostalismans.tooltip.mutual_trident_talisman.title": "相互三叉戟",
    "item.fargostalismans.tooltip.health_sharing_talisman.title": "生命共享",
    "item.fargostalismans.tooltip.food_sharing_talisman.title": "食物共享",
    "item.fargostalismans.tooltip.turtle_talisman.title": "乌龟",
    "item.fargostalismans.tooltip.mutual_sword_talisman": "每个佩戴护符的附近玩家增加5%的近战伤害，最多增加25%",
    "item.fargostalismans.tooltip.mutual_bow_talisman": "每个佩戴护符的附近玩家增加5%的远程伤害，最多增加25%",
    "item.fargostalismans.tooltip.mutual_trident_talisman": "每个佩戴护符的附近玩家增加5%的三叉戟伤害，最多增加25%",
    "item.fargostalismans.tooltip.health_sharing_talisman": "与最多两名附近玩家共享10%的治愈效果，最多共享20%",
    "item.fargostalismans.tooltip.food_sharing_talisman": "与最多两名附近玩家共享10%的食物饱和度，最多共享20%",
    "item.fargostalismans.tooltip.turtle_talisman": "将10%的所受伤害转移给佩戴护符的附近玩家，最多转移20%",
    
    "item.fargostalismans.force_of_overworld": "世界力量",
    "item.fargostalismans.force_of_nature": "自然力量",
    "item.fargostalismans.force_of_rejectors": "排斥者的力量",
    "item.fargostalismans.force_of_mystic": "神秘力量",
    "item.fargostalismans.force_of_warrior": "战士力量",
    "item.fargostalismans.force_of_explorer": "探险者力量",
    "item.fargostalismans.force_of_negative": "负面力量",
    "item.fargostalismans.force_of_environment": "环境力量",
    "item.fargostalismans.force_of_collaboration": "协作力量",
    
    "item.fargostalismans.tooltip.force_of_overworld": "结合了一些世界主题护符的能力",
    "item.fargostalismans.tooltip.force_of_nature": "结合了自然主题护符的能力",
    "item.fargostalismans.tooltip.force_of_rejectors": "结合了一些敌对主题护符的能力",
    "item.fargostalismans.tooltip.force_of_mystic": "结合了一些神秘主题护符的能力",
    "item.fargostalismans.tooltip.force_of_warrior": "结合了一些伤害主题护符的能力",
    "item.fargostalismans.tooltip.force_of_explorer": "结合了一些探索主题护符的能力",
    "item.fargostalismans.tooltip.force_of_negative": "结合了一些负面主题护符的能力",
    "item.fargostalismans.tooltip.force_of_environment": "结合了一些环境主题护符的能力",
    "item.fargostalismans.tooltip.force_of_collaboration": "结合了一些协作主题护符的能力",
    
    "item.fargostalismans.soul_of_minecraft": "Minecraft之魂",
    "item.fargostalismans.soul_of_flight_mastery": "飞行大师之魂",
    "item.fargostalismans.soul_of_colossus": "巨人之魂",
    "item.fargostalismans.soul_of_supersonic": "超音速之魂",
    "item.fargostalismans.soul_of_trawler": "拖网渔船之魂",
    "item.fargostalismans.soul_of_dimensions": "维度之魂",
    
    "item.fargostalismans.soul_of_flight_mastery_1": "飞行大师之魂 第1部分",
    "item.fargostalismans.soul_of_flight_mastery_2": "飞行大师之魂 第2部分",
    "item.fargostalismans.soul_of_colossus_1": "巨人之魂 第1部分",
    "item.fargostalismans.soul_of_colossus_2": "巨人之魂 第2部分",
    "item.fargostalismans.soul_of_supersonic_1": "超音速之魂 第1部分",
    "item.fargostalismans.soul_of_supersonic_2": "超音速之魂 第2部分",
    
    "item.fargostalismans.tooltip.soul_of_minecraft": "结合所有力量的能力",
    "item.fargostalismans.tooltip.soul_of_flight_mastery": "授予创造性飞行能力",
    "item.fargostalismans.tooltip.soul_of_colossus": "授予超人般的防御、生命值和对所有负面 debuffs 的免疫",
    "item.fargostalismans.tooltip.soul_of_supersonic": "授予超音速奔跑和飞行能力",
    "item.fargostalismans.tooltip.soul_of_trawler": "提高钓鱼的成功率",
    "item.fargostalismans.tooltip.soul_of_dimensions": "结合所有灵魂的能力",
    
    "item.fargostalismans.abominable_energy": "可憎的能量",
    "item.fargostalismans.tooltip.abominable_energy": "从Fargo的地牢中的宝藏室获取",
    
    "item.fargostalismans.ancient_wings_elytra": "古老的翅膀",
    "item.fargostalismans.astral_wings_elytra": "星界翅膀",
    "item.fargostalismans.blazing_wings_elytra": "炽热的翅膀",
    "item.fargostalismans.dragon_wings_elytra": "龙翼",
    "item.fargostalismans.dusty_wings_elytra": "尘土飞扬的翅膀",
    "item.fargostalismans.enchanted_wings_elytra": "附魔翅膀",
    "item.fargostalismans.ender_wings_elytra": "末影翅膀",
    "item.fargostalismans.forest_wings_elytra": "森林翅膀",
    "item.fargostalismans.frozen_wings_elytra": "冰冻翅膀",
    "item.fargostalismans.ghastly_wings_elytra": "恐怖的翅膀",
    "item.fargostalismans.oceans_fins_elytra": "海洋鳍翼",
    "item.fargostalismans.phantom_wings_elytra": "幽灵翅膀",
    "item.fargostalismans.volcanic_ash_elytra": "火山灰翅膀",
    "item.fargostalismans.wither_wings_elytra": "凋零翅膀",
    "item.fargostalismans.tooltip.craftingitem.scavenged": "从Fargo的地牢中的怪物处搜刮获得",
    
    "item.fargostalismans.hand_warmer": "手部暖器",
    "item.fargostalismans.obsidian_horseshoe": "黑曜石马蹄铁",
    "item.fargostalismans.worm_scarf": "虫子围巾",
    "item.fargostalismans.brain_of_confusion": "混乱之脑",
    "item.fargostalismans.pocket_mirror": "口袋镜子",
    "item.fargostalismans.charm_of_myths": "神话护符",
    "item.fargostalismans.bee_cloak": "蜜蜂斗篷",
    "item.fargostalismans.star_veil": "星辰面纱",
    "item.fargostalismans.shiny_stone": "闪亮石",
    "item.fargostalismans.hero_shield": "英雄盾牌",
    "item.fargostalismans.frozen_shield": "冰冻盾牌",
    "item.fargostalismans.ankh_shield": "安卡盾牌",
    "item.fargostalismans.tooltip.craftingitem.looted": "从Fargo的地牢中获取",
    
    "item.fargostalismans.aeolus_boots": "艾俄洛斯之靴",
    "item.fargostalismans.brain_scrambler": "脑部扰乱器",
    "item.fargostalismans.reindeer_bells": "驯鹿铃铛",
    "item.fargostalismans.ancient_horn": "古老的号角",
    "item.fargostalismans.mechanical_cart": "机械手推车",
    "item.fargostalismans.blessed_apple": "祝福的苹果",
    "item.fargostalismans.master_ninja_gear": "大师忍者装备",
    "item.fargostalismans.shield_of_cthulhu": "克苏鲁的盾牌",
    "item.fargostalismans.bundle_of_horseshoe_balloons": "马蹄铁气球束",
    "item.fargostalismans.amber_horseshoe_balloon": "琥珀马蹄铁气球",
    "item.fargostalismans.sweetheart_necklace": "甜心项链",
    "item.fargostalismans.flying_carpet": "飞毯",
    "item.fargostalismans.fatigued_vial": "疲劳药剂",
    "item.fargostalismans.withered_vial": "凋零药剂",
    "item.fargostalismans.nauseated_vial": "恶心药剂",
    "item.fargostalismans.poisoned_vial": "中毒药剂",
    "item.fargostalismans.weakened_vial": "虚弱药剂",
    "item.fargostalismans.fired_vial": "火焰药剂",
    "item.fargostalismans.slowed_vial": "减速药剂",
    "item.fargostalismans.blinded_vial": "失明药剂",
    "item.fargostalismans.tooltip.craftingitem.crafted": "制作物品",
    "item.fargostalismans.tooltip.craftingitem.component_1": "制作物品 第1部分",
    "item.fargostalismans.tooltip.craftingitem.component_2": "制作物品 第2部分",
    
    "item.fargostalismans.talisman_base_normal": "普通护符底座",
    "item.fargostalismans.talisman_base_advanced": "高级护符底座",
    "item.fargostalismans.talisman_base_epic": "史诗护符底座",
    "item.fargostalismans.talisman_base_legendary": "传奇护符底座",
    "item.fargostalismans.talisman_base_ultimate": "终极护符底座",
    "item.fargostalismans.talisman_base_godly": "神圣护符底座",
    
    "fargostalismans.subtitle.equip_talisman": "护符已装备",
    "fargostalismans.subtitle.unequip_talisman": "护符已卸下",
    
    "item.fargostalismans.tooltip.disabled_by_server": "服务器禁用护符",
    "item.fargostalismans.tooltip.disabled_by_client": "客户端已关闭护符",
    
    "effect.fargostalismans.air_talisman_effect": "临时空气护符",
    "effect.fargostalismans.amethyst_talisman_effect": "临时紫水晶护符",
    "effect.fargostalismans.apple_talisman_effect": "临时苹果护符",
    "effect.fargostalismans.architect_talisman_effect": "临时建筑师护符",
    "effect.fargostalismans.arctic_talisman_effect": "临时极地护符",
    "effect.fargostalismans.battle_talisman_effect": "临时战斗护符",
    "effect.fargostalismans.blaze_talisman_effect": "临时烈焰护符",
    "effect.fargostalismans.blinded_talisman_effect": "临时失明护符",
    "effect.fargostalismans.cactus_talisman_effect": "临时仙人掌护符",
    "effect.fargostalismans.copper_talisman_effect": "临时铜护符",
    "effect.fargostalismans.creeper_talisman_effect": "临时苦力怕护符",
    "effect.fargostalismans.day_talisman_effect": "临时白天护符",
    "effect.fargostalismans.diamond_talisman_effect": "临时钻石护符",
    "effect.fargostalismans.dragon_talisman_effect": "临时龙护符",
    "effect.fargostalismans.earth_talisman_effect": "临时大地护符",
    "effect.fargostalismans.emerald_talisman_effect": "临时绿宝石护符",
    "effect.fargostalismans.enchanting_talisman_effect": "临时附魔护符",
    "effect.fargostalismans.enderman_talisman_effect": "临时末影人护符",
    "effect.fargostalismans.fire_talisman_effect": "临时火焰护符",
    "effect.fargostalismans.fired_talisman_effect": "临时燃烧护符",
    "effect.fargostalismans.full_moon_talisman_effect": "临时满月护符",
    "effect.fargostalismans.ghast_talisman_effect": "临时恶魂护符",
    "effect.fargostalismans.glowstone_talisman_effect": "临时萤石护符",
    "effect.fargostalismans.gold_talisman_effect": "临时黄金护符",
    "effect.fargostalismans.iron_golem_talisman_effect": "临时铁傀儡护符",
    "effect.fargostalismans.iron_talisman_effect": "临时铁护符",
    "effect.fargostalismans.lapis_talisman_effect": "临时青金石护符",
    "effect.fargostalismans.librarian_talisman_effect": "临时图书管理员护符",
    "effect.fargostalismans.mooshroom_talisman_effect": "临时蘑菇牛护符",
    "effect.fargostalismans.nauseated_talisman_effect": "临时恶心护符",
    "effect.fargostalismans.nether_star_talisman_effect": "临时下界之星护符",
    "effect.fargostalismans.night_talisman_effect": "临时夜晚护符",
    "effect.fargostalismans.obsidian_talisman_effect": "临时黑曜石护符",
    "effect.fargostalismans.pickaxe_talisman_effect": "临时镐护符",
    "effect.fargostalismans.poisoned_talisman_effect": "临时中毒护符",
    "effect.fargostalismans.rain_talisman_effect": "临时雨天护符",
    "effect.fargostalismans.redstone_talisman_effect": "临时红石护符",
    "effect.fargostalismans.shulker_talisman_effect": "临时蝴蝶结护符",
    "effect.fargostalismans.skeleton_talisman_effect": "临时骷髅护符",
    "effect.fargostalismans.slowed_talisman_effect": "临时减速护符",
    "effect.fargostalismans.snowy_talisman_effect": "临时雪地护符",
    "effect.fargostalismans.spectral_talisman_effect": "临时光谱护符",
    "effect.fargostalismans.storm_talisman_effect": "临时风暴护符",
    "effect.fargostalismans.sun_talisman_effect": "临时太阳护符",
    "effect.fargostalismans.thorny_talisman_effect": "临时荆棘护符",
    "effect.fargostalismans.true_sun_talisman_effect": "临时真正的太阳护符",
    "effect.fargostalismans.undying_talisman_effect": "临时不朽护符",
    "effect.fargostalismans.vampiric_talisman_effect": "临时吸血护符",
    "effect.fargostalismans.vindicator_talisman_effect": "临时复仇者护符",
    "effect.fargostalismans.void_talisman_effect": "临时虚空护符",
    "effect.fargostalismans.water_talisman_effect": "临时水护符",
    "effect.fargostalismans.weakened_talisman_effect": "临时虚弱护符",
    "effect.fargostalismans.witch_talisman_effect": "临时女巫护符",
    "effect.fargostalismans.wither_talisman_effect": "临时凋零护符",
    "effect.fargostalismans.withered_talisman_effect": "临时凋零护符",
    "effect.fargostalismans.zombie_talisman_effect": "临时僵尸护符",
    "effect.fargostalismans.soul_of_colossus_effect": "临时泰坦之魂",
    "effect.fargostalismans.soul_of_flight_mastery_effect": "临时飞行掌控之魂",
    "effect.fargostalismans.soul_of_supersonic_effect": "临时超音速之魂",
    
    "block.fargostalismans.pedestal": "护符底座",
    "block.fargostalismans.tooltip.pedestal": "在AOE范围内对玩家施加护符效果",
    "block.fargostalismans.tooltip.pedestal2": "放置在特定方块上时半径会有所调整",
    "block.fargostalismans.tooltip.pedestal_1": "默认",
    "block.fargostalismans.tooltip.pedestal_2": "紫水晶块",
    "block.fargostalismans.tooltip.pedestal_3": "信标",
    "block.fargostalismans.tooltip.pedestal_4": "合唱花",
    "block.fargostalismans.tooltip.pedestal_1_blocks": "5",
    "block.fargostalismans.tooltip.pedestal_2_blocks": "9",
    "block.fargostalismans.tooltip.pedestal_3_blocks": "15",
    "block.fargostalismans.tooltip.pedestal_4_blocks": "20",
    "block.fargostalismans.tooltip.pedestal_radius": " 半径：",
    "key.category.fargostalismans": "Fargo的护符",
    "key.fargostalismansmod.opengui": "打开护符控制界面",
    "key.categories.fargostalismansmod": "Fargo的护符",
    "key.categories.fargostalismans.fov": "视野变化可能很大，但可以在辅助功能设置中的'视野效果'下调节",
    "item.fargostalismans.curse_removed": "物品上的诅咒已移除！",
    "item.fargostalismans.guide_book": "Fargo的护符指南",
    "screen.fargostalismans.header": "Fargo的护符配置",
    "screen.fargostalismans.node.talisman.header": "护符",
    "screen.fargostalismans.node.soul.header": "灵魂"
    
}

**Comment by STS15** [comment]
This is fantastic!  Thank you so much.  I never realized how far reaching this could be.  I hope you enjoy playing the mod!  Added in the next update!

Translated from Google:
这太棒了！非常感谢。我从未意识到这会产生如此深远的影响。希望你喜欢玩这个模组！
