### ISSUE TITLE
Force of Warrior does not provide Iron Golem modification

### ISSUE THREAD

**Issue by STS15** [STS15/Fargos-Talismans#33]
### Modpack

Yes

### Neoforge Version

21.1.73

### Mod Version

1.21-2.2.0

### Describe the issue

Iron golem health increase not functioning while wearing the force of warrior

### Expected behaviour

Should function

**Comment by STS15** [comment]
Switched curioTick to playerTick so that the talisman limited ticks when wearing other talismans but using the same provider

**Comment by STS15** [comment]
Fixed on latest update

**Comment by DMSledge** [comment]
FYI I'm still having this issue on 2.2.1
