### ISSUE TITLE
Force of Warrior stopped providing Iron Golem modification after status effect

### ISSUE THREAD

**Issue by apdjz** [STS15/Fargos-Talismans#35]
### Modpack

Yes

### Neoforge Version

21.1.74

### Mod Version

2.2.1

### Describe the issue

-Made Force of Warrior
-Equipped it to the charm slot
-Gain the buff
-Fought the warden. Got the debuff plague from Champions Mod :Plagued - Infects nearby creatures with a Poison effect
-Noticed my health was no long restoring to 200%
-Died. 

Modpack FTB Evolutions 1.3

**Comment by STS15** [comment]
Hi, this is already fixed in the latest version 2.2.21.  You'll need to update the mod in the pack.  If you're on a server, you may need to wait until the pack updates.
