### ISSUE TITLE
Allow access to the Talismans GUI through Forces & Soul of Minecraft

### ISSUE THREAD

**Issue by j-carrara** [STS15/Fargos-Talismans#36]
### What should be added or changed?

Getting to the Talismans GUI through a command is unintuitive and largely undocumented. (Discord is potentially the worst place to put things like this, it should be included in the guide book or mod landing pages)

The GUI could potentially be accessed through a right click, or a crouch right click with any force or the Soul of Minecraft in hand.

**Comment by STS15** [comment]
I don't disagree, but I've tried to make it very obvious there is a toggle GUI in game.  It's hotlinked on the main page in the in game guide book, on the mod page on Curse, and it's also listed in the discord.  Arguably I should make the command easier with less arguments.
![image](https://github.com/user-attachments/assets/cc09b1ec-a805-43da-9fc3-e74cffb5dc62)
